### ISSUE TITLE
anti drop?

### ISSUE THREAD

**Issue by nayfaan** [EvenSafe789/Plugins#2]
can you do the opposite also where instead of anti pickup make a anti drop?

**Comment by EvenSafe789** [comment]
That sounds like a great idea, I just need a few more details then I can start work.

Would you not be able to drop items with commands? For example: a command to enable/disable dropping items, just like AntiPickup, but for dropping?

**Comment by EvenSafe789** [comment]
Hey, I've added this :)

http://www.spigotmc.org/resources/antipickup.1234/

**Comment by nayfaan** [comment]
Haha no. Thank you :D

**Comment by nayfaan** [comment]
Haha no. Thank you :D
